import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { cookies } from "next/headers";
import { getCurrentLocale } from "@/lib";
import { I18nProviderClient } from "@/lib/index.client";
import { COOKIES_KEYS } from "@/shared/consts";
import { Footer, Header } from "@/widgets";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [locale, cookieStore] = await Promise.all([getCurrentLocale(), cookies()]);

  const theme = cookieStore.get(COOKIES_KEYS.theme)?.value ?? "dark";

  return (
    <html lang={locale} className={theme}>
      <I18nProviderClient locale={locale}>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Header />
          <main> {children}</main>
          <Footer />
        </body>
      </I18nProviderClient>
    </html>
  );
}
