import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "../globals.css";
import { cookies } from "next/headers";
import { getCurrentLocale } from "@/lib";
import { I18nProviderClient } from "@/lib/index.client";
import { COOKIES_KEYS } from "@/shared/consts";
import { cn } from "@/shared/utils";
import { Footer, Header } from "@/widgets";

export const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [locale, cookieStore] = await Promise.all([getCurrentLocale(), cookies()]);

  const theme = cookieStore.get(COOKIES_KEYS.theme)?.value ?? "dark";

  return (
    <html lang={locale} className={theme}>
      <body className={cn(ibmPlexSans.variable, "antialiased flex flex-col")}>
        <I18nProviderClient locale={locale}>
          <Header currentTheme={theme as "light" | "dark"} />
          <main> {children}</main>
          <Footer />
        </I18nProviderClient>
      </body>
    </html>
  );
}
